spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contentmanager
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB #aumenta o limite do tamanho do arquivo de 1MB para 20MB
      max-request-size: 2MB


# Production
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/contentmanager
